rootdir='/srv'
outdir='/srv/eddata/namedbodies'
#conntype = 'mysql.connector'
conntype = 'mysqlclient'
#conntype = 'pymysql'
sqluser = 'eddata'
sqlhost = 'localhost'
sqlpass = 'P@ssw0rd1234'
sqldb = 'eddata_eddn'

