CREATE TABLE `EDSMFiles` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`FileName` VARCHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`Date` DATE NULL DEFAULT NULL,
	`LineCount` INT(11) NULL DEFAULT NULL,
	`CompressedSize` BIGINT(20) NULL DEFAULT NULL,
	`UncompressedSize` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;;
