CREATE TABLE `Regions` (
	`Id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(128) NOT NULL COLLATE 'utf8_general_ci',
	`X0` FLOAT(30,6) NULL DEFAULT NULL,
	`Y0` FLOAT(30,6) NULL DEFAULT NULL,
	`Z0` FLOAT(30,6) NULL DEFAULT NULL,
	`SizeX` INT(11) NULL DEFAULT NULL,
	`SizeY` INT(11) NULL DEFAULT NULL,
	`SizeZ` INT(11) NULL DEFAULT NULL,
	`RegionAddress` INT(11) NULL DEFAULT NULL,
	`IsHARegion` BIT(1) NOT NULL,
	`IsPermitLocked` BIT(1) NOT NULL DEFAULT b'0',
	`HARegionPriority` INT(11) NULL DEFAULT NULL,
	`ValidFrom` DATETIME NOT NULL DEFAULT '2014-01-01 00:00:00',
	`ValidUntil` DATETIME NOT NULL DEFAULT '9999-12-31 00:00:00',
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `IX_Name` (`Name`) USING BTREE,
	UNIQUE INDEX `RegionAddress` (`RegionAddress`) USING BTREE,
	INDEX `IX_HACorner` (`IsHARegion`, `Z0`, `Y0`, `X0`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;;
