CREATE TABLE `SystemBodyDesignations` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`BodyCategory` TINYINT(3) UNSIGNED NOT NULL,
	`Stars` SMALLINT(6) NOT NULL,
	`Planet` TINYINT(3) UNSIGNED NOT NULL,
	`Moon1` TINYINT(3) UNSIGNED NOT NULL,
	`Moon2` TINYINT(3) UNSIGNED NOT NULL,
	`Moon3` TINYINT(3) UNSIGNED NOT NULL,
	`BodyCategoryDescription` VARCHAR(20) DEFAULT NULL AS (case `BodyCategory` when 1 then 'StellarBarycentre' when 2 then 'StellarBody' when 3 then 'Belt' when 4 then 'AsteroidCluster' when 5 then 'PlanetaryBarycentre' when 6 then 'PlanetaryBody' when 7 then 'PlanetaryRing' when 8 then 'Moon1Barycentre' when 9 then 'Moon1' when 10 then 'Moon1Ring' when 11 then 'Moon2Barycentre' when 12 then 'Moon2' when 13 then 'Moon2Ring' when 14 then 'Moon3' when 15 then 'Comet' when 16 then 'PlanetComet' when 17 then 'Moon1Comet' when 18 then 'Moon2Comet' when 19 then 'Nebula' else 'Unknown' end) virtual COLLATE 'utf8_general_ci',
	`BodyDesignation` VARCHAR(128) DEFAULT NULL AS (concat(case when `Stars` = 0 then '' else ' ' end,case when `Stars` & 1 = 1 then 'A' else '' end,case when `Stars` & 2 = 2 then 'B' else '' end,case when `Stars` & 4 = 4 then 'C' else '' end,case when `Stars` & 8 = 8 then 'D' else '' end,case when `Stars` & 16 = 16 then 'E' else '' end,case when `Stars` & 32 = 32 then 'F' else '' end,case when `Stars` & 64 = 64 then 'G' else '' end,case when `Stars` & 128 = 128 then 'H' else '' end,case when `Stars` & 256 = 256 then 'I' else '' end,case when `Stars` & 512 = 512 then 'J' else '' end,case when `Stars` & 1024 = 1024 then 'K' else '' end,case when `Stars` & 2048 = 2048 then 'L' else '' end,case when `Stars` & 4096 = 4096 then 'M' else '' end,case when `Stars` & 8192 = 8192 then 'N' else '' end,case when `Stars` & 16384 = 16384 then 'O' else '' end,case when `BodyCategory` = 19 then ' Nebula' when `Planet` = 0 then '' when `BodyCategory` in (3,4) then concat(' ',char(`Planet` + 64),' Belt',case when `Moon1` = 0 then '' else concat(' Cluster ',`Moon1`) end) when `BodyCategory` = 15 then concat(' Comet ',`Planet`) else concat(' ',`Planet`,case when `Moon1` = 0 then '' when `BodyCategory` = 5 then concat('+',`Planet` + 1,case when `Moon1` >= 2 then concat('+',`Planet` + 2,case when `Moon1` >= 3 then concat('+',`Planet` + 3,case when `Moon1` = 3 then '' when `Moon1` = 4 then concat('+',`Planet` + 4) else '+...' end) else '' end) else '' end) when `BodyCategory` = 7 then concat(' ',char(`Moon1` + 64),' Ring') when `BodyCategory` = 16 then concat(' Comet ',`Moon1`) else concat(' ',char(`Moon1` + 96),case when `Moon2` = 0 then '' when `BodyCategory` = 8 then concat('+',char(`Moon1` + 96 + 1),case when `Moon2` >= 2 then concat('+',char(`Moon1` + 96 + 2),case when `Moon2` >= 3 then concat('+',char(`Moon1` + 96 + 3),case when `Moon2` = 3 then '' when `Moon2` = 4 then concat('+',char(`Moon1` + 96 + 4)) else '+...' end) else '' end) else '' end) when `BodyCategory` = 10 then concat(' ',char(`Moon2` + 64),' Ring') when `BodyCategory` = 17 then concat(' Comet ',`Moon2`) else concat(' ',char(`Moon2` + 96),case when `Moon3` = 0 then '' when `BodyCategory` = 11 then concat('+',char(`Moon2` + 96 + 1),case when `Moon3` >= 2 then concat('+',char(`Moon2` + 96 + 2),case when `Moon3` >= 3 then concat('+',char(`Moon2` + 96 + 3),case when `Moon3` = 3 then '' when `Moon3` = 4 then concat('+',char(`Moon2` + 96 + 4)) else '+...' end) else '' end) else '' end) when `BodyCategory` = 13 then concat(' ',char(`Moon3` + 64),' Ring') when `BodyCategory` = 18 then concat(' Comet ',`Moon3`) else concat(' ',char(`Moon3` + 96)) end) end) end) end)) stored COLLATE 'utf8_general_ci',
	`IsUsed` BIT(1) NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `BodyPgDesig` (`Stars`, `BodyCategory`, `Planet`, `Moon1`, `Moon2`, `Moon3`) USING BTREE,
	UNIQUE INDEX `BodyDesignation` (`BodyDesignation`) USING BTREE,
	INDEX `BodyPgDesigId` (`Stars`, `BodyCategory`, `Planet`, `Moon1`, `Moon2`, `Moon3`, `Id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;;
